# Generated by Django 5.0.6 on 2026-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datasets", "0002_add_file_version_to_dataset"),
        ("reports", "0001_initial"),
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="qualityreport",
            index=models.Index(
                fields=["dataset", "-generated_at"], name="idx_report_dataset"
            ),
        ),
        migrations.AddIndex(
            model_name="rulefinding",
            index=models.Index(fields=["quality_report"], name="idx_finding_report"),
        ),
    ]
