# Generated by Django 5.0.6 on 2026-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_missing_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualityreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("healthy", "Healthy"),
                    ("warning", "Warning"),
                    ("failing", "Failing"),
                ],
                default="failing",
                max_length=20,
            ),
        ),
    ]
