# Generated by Django 5.0.6 on 2026-06-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_replace_status_with_quality_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityreport",
            name="dataset_file_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="qualityreport",
            name="dataset_file_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
