# Generated by Django 6.0.5 on 2026-06-01 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("column_name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("null_check", "Null Check"),
                            ("type_check", "Type Check"),
                            ("range_check", "Range Check"),
                            ("uniqueness_check", "Uniqueness Check"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rule_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        db_column="dataset_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "db_table": "validation_rules",
                "ordering": ["created_at"],
                "indexes": [models.Index(fields=["dataset"], name="idx_rule_dataset")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "column_name", "rule_type"),
                        name="unique_rule_per_column_type",
                    )
                ],
            },
        ),
    ]
